# SPDX-FileCopyrightText: © 2022–2023 Kevin Lu
# SPDX-Licence-Identifier: LGPL-3.0-or-later
name: Update wikitext from Yugipedia with recent changes

on:
  workflow_dispatch:
    inputs:
      since:
        description: Mediawiki API timestamp for change log start time
        required: false
  # Note: cron schedule is highly unreliable
  repository_dispatch:
    types:
      - update
  schedule:
    - cron: "0 2/4 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - run: pip install -r src/requirements.txt
      # https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
      - name: Get the last time this workflow ran
        id: last-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(gh api /repos/${{ github.repository }}/actions/runs | jq --raw-output '[.workflow_runs[] | select(.path == ".github/workflows/update.yml" and .conclusion == "success")][0].created_at')
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
      - working-directory: wikitext/cards
        run: python3 ../../src/incremental.py Duel_Monsters_cards "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      # - working-directory: wikitext/duel-links-cards
      #   run: python3 ../../src/incremental.py "Yu-Gi-Oh!_Duel_Links_cards" "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      # - working-directory: wikitext/duel-links-skills
      #   run: python3 ../../src/incremental.py "Yu-Gi-Oh!_Duel_Links_Skills" "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/rush
        run: python3 ../../src/incremental.py Rush_Duel_cards "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/speed
        run: python3 ../../src/incremental.py Skill_Cards "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/archetypes
        run: python3 ../../src/incremental.py TCG_and_OCG_archetypes "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/master-duel-cards
        run: python3 ../../src/incremental.py "Yu-Gi-Oh!_Master_Duel_cards" "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/master-duel-limit-regulation
        run: python3 ../../src/incremental.py "Yu-Gi-Oh!_Master_Duel_Forbidden_%26_Limited_Lists" "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/tokens
        run: python3 ../../src/incremental.py Tokens "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - working-directory: wikitext/konami-index
        run: python3 ../../src/incremental.py Cards_by_Konami_index_number "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}"
      - id: commit
        uses: DawnbrandBots/yaml-yugi/.github/actions/commit-push@master
        if: always()
        with:
          message: "Yugipedia recent changes: ${{ github.run_number }} (${{ github.run_id }})"
      - if: steps.commit.outputs.status > 0
        name: Trigger yaml-yugi workflow
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: gh workflow run merge.yaml --repo DawnbrandBots/yaml-yugi
    outputs:
      status: ${{ steps.commit.outputs.status }}
  validate:
    needs: download
    if: needs.download.outputs.status > 0 && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Duel Monsters cards do not contain Rush Duel cards (naïve check)
        run: |
          ! grep RD/ -R wikitext/cards --include='*.yaml'
