# SPDX-FileCopyrightText: © 2022 Kevin Lu
# SPDX-Licence-Identifier: LGPL-3.0-or-later
name: Update wikitext from Yugipedia with recent changes

on:
  workflow_dispatch:
    inputs:
      since:
        description: Mediawiki API timestamp for change log start time
        required: false
      grccontinue:
        description: Mediawiki API grccontinue parameter
        required: false
  # Note: cron schedule is highly unreliable
  repository_dispatch:
    types:
      - update
  schedule:
    - cron: "0 2/4 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: pip
      - run: pip install -r src/requirements.txt
      # https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
      - name: Get the last time this workflow ran
        id: last-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(gh api /repos/${{ github.repository }}/actions/runs | jq --raw-output '[.workflow_runs[] | select(.path == ".github/workflows/update.yml" and .conclusion == "success")][0].created_at')
          echo "::set-output name=timestamp::$TIMESTAMP"
      - run: cd wikitext/cards && python3 ../../src/incremental.py "${{ github.event.inputs.since || steps.last-run.outputs.timestamp }}" # "${{ github.event.inputs.grccontinue }}"
      - name: Commit
        if: ${{ always() }}
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Yugipedia recent changes"
          git pull --rebase
          git push
      - name: Trigger yaml-yugi workflow
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: gh workflow run merge.yaml --repo DawnbrandBots/yaml-yugi
